/* Lousa de Estudos, versão 55 */
(()=>{
if(window.__lousaV55)return;window.__lousaV55=true;
const KEY='lousa:v55:dict:';
const BASE={
 a:['Pode ser artigo feminino singular, como em “a gansa”. Também pode aparecer como preposição em expressões como “a bordo”.','Use antes de um nome feminino específico ou em algumas expressões.','A menina leu o texto.'],
 o:['Artigo masculino singular usado antes de um nome específico.','Use antes de substantivos masculinos.','O astronauta fez o teste.'],
 de:['Preposição que liga palavras e pode indicar origem, assunto, posse, material ou relação.','Observe a relação entre as palavras ligadas por ela.','Uma pergunta de Português.'],
 do:['Junção de “de” com “o”.','Liga palavras a um termo masculino.','A ideia do texto.'],
 da:['Junção de “de” com “a”.','Liga palavras a um termo feminino.','A comida da nave.'],
 em:['Preposição que pode indicar lugar, tempo, situação ou modo.','Veja se a frase fala de onde, quando ou em que situação algo acontece.','Em um teste.'],
 no:['Junção de “em” com “o”.','Pode indicar lugar, tempo ou situação.','No texto, procure uma pista.'],
 na:['Junção de “em” com “a”.','Pode indicar lugar, tempo ou situação.','Na história, houve um problema.'],
 para:['Preposição que pode indicar destino, objetivo ou finalidade.','Veja se a frase mostra para onde algo vai ou para que algo serve.','Estudar para aprender.'],
 por:['Preposição que pode indicar causa, motivo, passagem, meio ou autoria.','O sentido depende da frase completa.','Feito por alunos.'],
 com:['Preposição que pode indicar companhia, instrumento, modo ou relação.','Veja o que está sendo ligado na frase.','Escrever com lápis.'],
 e:['Palavra que liga ideias, palavras ou ações e acrescenta uma informação à outra.','Use para juntar elementos.','Leu o texto e respondeu.'],
 ou:['Palavra que apresenta escolha ou possibilidade.','Use quando existem possibilidades diferentes.','Lápis ou caneta.'],
 que:['Palavra com vários usos. Pode ligar partes da frase, retomar uma palavra ou introduzir uma pergunta.','Leia a frase inteira para entender o papel dela.','O que aconteceu?'],
 se:['Palavra com vários usos. Pode indicar condição ou hipótese.','Leia a frase inteira para entender o papel dela.','Se chover, ficaremos em casa.'],
 como:['Pode indicar comparação, modo ou introduzir uma pergunta sobre a maneira como algo acontece.','Veja se a frase compara ou pergunta de que maneira.','Como a comida mudou?'],
 qual:['Palavra usada para perguntar ou identificar algo.','Descubra exatamente qual elemento a pergunta procura.','Qual é a ideia principal?'],
 quando:['Palavra relacionada ao tempo.','Procure em que momento algo aconteceu.','Quando ocorreu o teste?'],
 onde:['Palavra usada para perguntar ou indicar lugar.','Procure uma informação de localização.','Onde aconteceu a história?'],
 quem:['Palavra usada para perguntar ou indicar pessoa.','Procure quem praticou ou recebeu a ação.','Quem participou?'],
 porque:['Palavra usada para apresentar causa, motivo ou explicação.','Use quando estiver explicando a razão de algo.','Melhorou porque a tecnologia avançou.'],
 'por que':['Expressão usada em perguntas para descobrir causa ou motivo.','Pense “por qual motivo?”.','Por que isso aconteceu?'],
 conflito:['Em uma história, é o problema principal que movimenta os acontecimentos.','Pense no momento em que as coisas começaram a dar errado.','O conflito muda o rumo da história.'],
 'inferência':['Conclusão feita juntando pistas do texto com o que já sabemos, mesmo sem a resposta estar escrita exatamente.','Junte as pistas antes de concluir.','A inferência nasce das pistas.'],
 'explícita':['Algo dito de forma clara e direta.','Procure a informação escrita claramente no texto.','Uma informação explícita aparece diretamente.'],
 principal:['Aquilo que é mais importante ou central.','Procure o que melhor resume o assunto.','A ideia principal resume o texto.'],
 concluir:['Chegar a uma ideia depois de observar informações e pensar sobre elas.','Junte as pistas antes de formar a conclusão.','Podemos concluir pelas pistas.'],
 explique:['Pedido para tornar uma ideia clara, mostrando como ou por que algo acontece.','Não escreva só uma palavra, mostre o raciocínio.','Explique como você pensou.'],
 compare:['Pedido para observar semelhanças e diferenças.','Veja o que é igual e o que mudou.','Compare o começo e o final.'],
 calcule:['Pedido para fazer as operações necessárias e descobrir um resultado.','Identifique os números e a operação.','Calcule o total.']
};
const norm=v=>String(v||'').trim().toLocaleLowerCase('pt-BR').replace(/[“”"'´`’.,;:!?()[\]{}<>]/g,'');
const plain=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function all(){try{return Object.values(subjects).flatMap(s=>(s.lessons||[]).flatMap(l=>(l.questions||[]).map(q=>({s,l,q}))));}catch(e){return[]}}
function rewrite(x){let t=String(x||'').trim(),m={
'Qual alternativa mostra uma inferência correta?':'Que inferência correta podemos fazer a partir das informações do texto? Explique com suas palavras.',
'Podemos concluir que comer no espaço:':'O que podemos concluir sobre como é comer no espaço? Explique com suas palavras.',
'Se o texto usa a expressão “Bingo!”, o resultado do teste foi visto como:':'Como o resultado do teste foi visto no texto? Use a expressão “Bingo!” como pista para explicar.',
'A palavra “práticas”, no texto, quer dizer principalmente:':'O que a palavra “práticas” quer dizer nesse texto? Explique usando o contexto.',
'O texto fala principalmente sobre:':'Sobre o que o texto fala principalmente? Escreva a ideia central com suas palavras.',
'Esse texto é melhor classificado como:':'Que tipo de texto é esse? Explique qual pista ajudou você a perceber.'};if(m[t])return m[t];
t=t.replace(/^Qual alternativa (?:mostra|apresenta|indica)\s+/i,'Explique o que ').replace(/^Assinale a alternativa que\s+/i,'Explique o que ').replace(/^Marque a alternativa que\s+/i,'Explique o que ').replace(/^Escolha a alternativa que\s+/i,'Explique o que ').replace(/\bqual alternativa\b/gi,'qual resposta');
if(/quer dizer principalmente:\s*$/i.test(t))t=t.replace(/\s*quer dizer principalmente:\s*$/i,' quer dizer nesse contexto? Explique com suas palavras.');
else if(/representa:\s*$/i.test(t))t=t.replace(/\s*representa:\s*$/i,' representa? Explique com suas palavras.');
else if(/resulta em:\s*$/i.test(t))t=t.replace(/\s*resulta em:\s*$/i,' resulta em quanto? Mostre o cálculo.');
else if(/fala principalmente sobre:\s*$/i.test(t))t=t.replace(/\s*fala principalmente sobre:\s*$/i,' fala principalmente sobre o quê?');
if(/:\s*$/.test(t))t=t.replace(/:\s*$/,'?');return t}
function kind(x){let t=plain(String(x||'').toLowerCase());if(/por que|porque|motivo|causa/.test(t))return'causa';if(/significa|quer dizer|sentido|expressao|palavra/.test(t))return'sentido';if(/concluir|inferencia|inferir|deduzir/.test(t))return'inferir';if(/principal|ideia central|assunto/.test(t))return'principal';if(/conflito|problema/.test(t))return'conflito';if(/quando|tempo|primeiro|depois|antes|sequencia|ordem/.test(t))return'tempo';if(/onde|lugar|local/.test(t))return'lugar';if(/quem|personagem/.test(t))return'pessoa';if(/compare|diferenca|semelhanca|mudou|mudanca/.test(t))return'comparar';if(/calcule|quanto|total|troco|resultado|multiplic|som|subtra|divid|porcent|fracao|decimal/.test(t))return'conta';if(/explique|com suas palavras|justifique/.test(t))return'explicar';return'buscar'}
function help(q){return({
causa:'A pergunta quer o motivo de alguma coisa. Volte ao trecho em que isso acontece e procure o que ocorreu antes para causar essa situação. Depois explique a relação com suas palavras.',
sentido:'Leia a frase inteira, a frase anterior e a seguinte. Pense qual sentido combina com aquela situação. Se precisar, pesquise a palavra no Dicionário.',
inferir:'A resposta pode não estar escrita exatamente. Junte duas ou mais pistas do texto e pense no que elas permitem entender. Escreva uma conclusão sustentada pelo texto.',
principal:'Pense no texto inteiro. Se você tivesse que contar em uma frase sobre o que ele fala, qual informação não poderia faltar?',
conflito:'Conflito é o problema principal da história. Descubra em que momento as coisas começaram a dar errado e qual dificuldade passou a movimentar os acontecimentos.',
tempo:'Procure palavras que mostram ordem ou tempo, como antes, depois, primeiro, no começo e no fim.',
lugar:'A pergunta procura um lugar. Volte ao trecho e procure onde a ação aconteceu.',
pessoa:'A pergunta procura uma pessoa ou personagem. Veja quem praticou a ação citada.',
comparar:'Separe as duas situações. Pense no que era de um jeito antes e no que passou a ser diferente depois.',
conta:'Identifique os números e o que a pergunta quer encontrar. Pense qual operação liga esses valores. Faça a conta na lousa e confira se o resultado faz sentido.',
explicar:'A pergunta quer mais do que uma palavra. Responda e acrescente uma frase dizendo como você descobriu isso ou por que faz sentido.',
buscar:'Leia a pergunta devagar e descubra exatamente o que ela quer saber. Depois procure no texto ou no conteúdo uma pista diretamente ligada ao pedido.'})[kind(q?.text)]}
function rules(){all().forEach(({q})=>{q.type='open';q.text=rewrite(q.text);q.reviewLabel='💡 Ajuda para entender a pergunta';q.review=help(q);q.reviewVisual=''});if(typeof buildPreQuestionReview==='function')buildPreQuestionReview=q=>`<div class="reviewLabel">💡 Ajuda para entender a pergunta</div><div class="reviewLead">${esc(help(q))}</div><div class="v55Reminder">A ajuda mostra o caminho, mas não entrega a resposta.</div>`;if(typeof v25BuildHint!=='undefined')v25BuildHint=q=>`<div class="v28Help"><p>${esc(help(q))}</p><div class="v55Reminder">A ajuda mostra o caminho, mas não entrega a resposta.</div></div>`}
function wordMap(){let m=new Map;all().forEach(({q})=>{let t=String(q.text||'');(t.match(/[A-Za-zÀ-ÖØ-öø-ÿ0-9%]+/g)||[]).forEach(r=>{let w=norm(r);if(!w)return;if(!m.has(w))m.set(w,[]);let a=m.get(w);if(a.length<3)a.push(t)})});return m}let WORDS=wordMap();
function local(w){let k=norm(w),d=BASE[k];if(!d){let p=plain(k),h=Object.keys(BASE).find(x=>plain(x)===p);d=BASE[h]}return d?{meaning:d[0],use:d[1],examples:[d[2]]}:null}
async function wiki(w){let title=norm(w);async function get(t){let u='https://pt.wiktionary.org/w/api.php?action=query&format=json&origin=*&redirects=1&prop=extracts&exintro=1&explaintext=1&titles='+encodeURIComponent(t),r=await fetch(u,{cache:'force-cache'});if(!r.ok)return null;let j=await r.json(),p=Object.values(j?.query?.pages||{}).find(x=>!x.missing),x=String(p?.extract||'').replace(/\s+/g,' ').trim();if(!x)return null;if(x.length>620)x=x.slice(0,620).replace(/\s+\S*$/,'')+'...';return{meaning:x,use:'Confira qual sentido combina com a frase da pergunta.',examples:[],source:'Wikcionário'}}return get(title)}
async function lookup(w){let k=norm(w),d=local(k);if(d)return d;try{d=JSON.parse(localStorage.getItem(KEY+k)||'null')}catch(e){}if(d)return d;try{d=await wiki(k)}catch(e){}if(!d){let c=WORDS.get(k)?.[0];d={meaning:'Esta palavra faz parte do vocabulário da pergunta. Leia o sentido junto com a frase completa.',use:c?'Ela aparece nesta pergunta: “'+c+'”':'Observe as palavras que aparecem antes e depois dela.',examples:[]}}try{localStorage.setItem(KEY+k,JSON.stringify(d))}catch(e){}return d}
function css(){if(document.getElementById('v55css'))return;let s=document.createElement('style');s.id='v55css';s.textContent=`.v55Reminder{margin-top:10px;padding:10px 12px;border-radius:13px;background:#f5f8ff;border:1px solid #dfe8f7;color:#54647a;font-size:12px;font-weight:800}.v55Fab{position:fixed;right:18px;bottom:18px;z-index:90000;min-height:50px;padding:0 16px;border:0;border-radius:17px;background:#5f2bd1;color:#fff;font-weight:950;box-shadow:0 14px 34px #532ba04d}.v55Ov{position:fixed;inset:0;z-index:91000;display:none;align-items:flex-end;justify-content:center;padding:16px;background:#0f172a85;backdrop-filter:blur(5px)}.v55Ov.show{display:flex}.v55Dlg{width:min(100%,620px);max-height:90vh;display:flex;flex-direction:column;background:#fff;border-radius:26px;overflow:hidden}.v55Top{display:flex;justify-content:space-between;gap:12px;padding:20px;border-bottom:1px solid #ececf4;background:#faf8ff}.v55Top h3{margin:0}.v55Top p{margin:5px 0 0;color:#6b6677;font-size:13px}.v55Close{width:38px;height:38px;border:0;border-radius:12px;background:#eee9fa;color:#5f2bd1;font-size:24px}.v55Body{padding:16px 18px 20px;overflow:auto}.v55Row{display:flex;gap:9px}.v55In{flex:1;min-width:0;height:48px;border:1px solid #dcd6e8;border-radius:14px;padding:0 14px;font-size:16px}.v55Go{border:0;border-radius:14px;padding:0 15px;background:#5f2bd1;color:#fff;font-weight:900}.v55Res{margin-top:14px}.v55Card{padding:18px;border:1px solid #e5e0ef;border-radius:19px}.v55Card h4{margin:0;color:#3b245f;font-size:24px}.v55Use{margin-top:12px;padding:12px;border-radius:14px;background:#f8f5ff}.v55Small{margin-top:8px;font-size:12px;line-height:1.5;color:#687080}.v55Words{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.v55Chip{border:1px solid #e0d9ea;background:#faf8ff;color:#5b3b8f;border-radius:999px;padding:7px 10px;font-size:12px;font-weight:800}@media(min-width:700px){.v55Ov{align-items:center}}`;document.head.appendChild(s)}
function dictionary(){css();if(document.querySelector('.v55Fab'))return;let b=document.createElement('button');b.className='v55Fab';b.textContent='📚 Dicionário';document.body.appendChild(b);let o=document.createElement('div');o.className='v55Ov';o.innerHTML=`<div class="v55Dlg"><div class="v55Top"><div><h3>Dicionário das perguntas</h3><p>Pesquise qualquer palavra, até palavras simples como “a”.</p></div><button class="v55Close">×</button></div><div class="v55Body"><div class="v55Row"><input class="v55In" type="search" placeholder="Digite uma palavra"><button class="v55Go">Pesquisar</button></div><div class="v55Res"></div><div class="v55Words"></div></div></div>`;document.body.appendChild(o);let i=o.querySelector('.v55In'),r=o.querySelector('.v55Res'),w=o.querySelector('.v55Words');function fill(){WORDS=wordMap();w.innerHTML='';[...WORDS.keys()].sort((a,b)=>a.localeCompare(b,'pt-BR')).slice(0,180).forEach(x=>{let c=document.createElement('button');c.className='v55Chip';c.textContent=x;c.onclick=()=>{i.value=x;go()};w.appendChild(c)})}async function go(){let x=norm(i.value);if(!x){r.innerHTML='<div class="v55Card">Digite uma palavra.</div>';return}r.innerHTML='<div class="v55Card">Procurando...</div>';let d=await lookup(x),ctx=WORDS.get(x)||[];r.innerHTML=`<div class="v55Card"><h4>${esc(x)}</h4><p>${esc(d.meaning||'')}</p>${d.use?`<div class="v55Use"><strong>Como entender ou usar:</strong><br>${esc(d.use)}</div>`:''}${(d.examples||[]).map(y=>`<div class="v55Small">Exemplo: ${esc(y)}</div>`).join('')}${d.source?`<div class="v55Small">Fonte: ${esc(d.source)}</div>`:''}${ctx.map(y=>`<div class="v55Small">Onde aparece: ${esc(y)}</div>`).join('')}</div>`}b.onclick=()=>{fill();o.classList.add('show');setTimeout(()=>i.focus(),50)};o.querySelector('.v55Close').onclick=()=>o.classList.remove('show');o.onclick=e=>{if(e.target===o)o.classList.remove('show')};o.querySelector('.v55Go').onclick=go;i.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();go()}};fill()}
function hook(){if(typeof renderLesson!=='function'||window.__lousaV55Hook)return;window.__lousaV55Hook=true;let old=renderLesson;renderLesson=function(l){(l?.questions||[]).forEach(q=>{q.type='open';q.text=rewrite(q.text);q.review=help(q);q.reviewVisual=''});let z=old(l);WORDS=wordMap();return z}}
function init(){rules();WORDS=wordMap();hook();dictionary()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
