/* Lousa de Estudos, versão 70: Português segue o formato do livro */
(()=>{
if(window.__lousaV70)return;window.__lousaV70=true;window.__lousaCurrentContentVersion=70;
const DATA=(window.__lousaV70Data||[]).slice().sort((a,b)=>a.n-b.n);
const clone=v=>{try{return JSON.parse(JSON.stringify(v))}catch(e){return v}};
function makeLessons(){return DATA.map(l=>({key:l.k,emoji:'📘',title:'Aula '+l.n,subtitle:l.t,desc:'Livro do Estudante • Língua Portuguesa • '+l.t,mission:'Língua Portuguesa • Aula '+l.n,passageTitle:l.pt,passage:l.p,questions:l.q.map((q,qi)=>{let x={id:'lp70_'+l.n+'_'+(qi+1),bookNumber:q.n,type:q.o?'mcq':'open',text:q.t,reviewLabel:'📘 Atividade do livro',review:q.o?'Leia o enunciado e escolha uma das alternativas apresentadas no livro.':'Responda como no livro, usando a lousa para escrever.',reviewVisual:''};if(q.o){x.options=clone(q.o);x.correct=q.c}return x})}))}
const BOOK=makeLessons(),originals=new Map;BOOK.forEach(l=>l.questions.forEach(q=>originals.set(q.id,clone(q))));
function restore(q){const o=originals.get(q&&q.id);if(!o)return;['bookNumber','type','text','options','correct','reviewLabel','review','reviewVisual'].forEach(k=>Object.prototype.hasOwnProperty.call(o,k)?q[k]=clone(o[k]):delete q[k])}
function install(){try{const s=subjects&&subjects.portuguese;if(!s)return;s.lessons=clone(BOOK);s.homeTitle='Língua Portuguesa • Volume 3';s.homeDescription='Atividades organizadas conforme o Livro do Estudante do 5º ano. Questões de múltipla escolha mantêm as alternativas do livro; questões abertas continuam com a lousa.';s.hint='Abra uma aula e responda no mesmo formato do livro.';s.chips=['📘 Livro do Estudante','✍️ Questões abertas','🔤 Múltipla escolha'];if(typeof currentSubjectKey!=='undefined'&&currentSubjectKey==='portuguese'){lessons=s.lessons;if(typeof renderTopicCards==='function')renderTopicCards()}}catch(e){console.error('v70',e)}}
function restoreAll(){try{(subjects.portuguese.lessons||[]).forEach(l=>l.questions.forEach(restore))}catch(e){}}
function protect(){if(typeof renderLesson!=='function'||window.__lousaV70Protect)return;window.__lousaV70Protect=true;const old=renderLesson;renderLesson=function(l){if(typeof currentSubjectKey==='undefined'||currentSubjectKey!=='portuguese')return old.apply(this,arguments);restoreAll();const rel=[];(l&&l.questions||[]).forEach(q=>{const o=originals.get(q.id);if(!o)return;['type','text'].forEach(k=>{try{Object.defineProperty(q,k,{configurable:true,enumerable:true,get(){return clone(o[k])},set(){}});rel.push(()=>{try{delete q[k]}catch(e){}})}catch(e){}})});try{return old.apply(this,arguments)}finally{rel.forEach(f=>f());restoreAll()}}}
function numbers(){if(typeof buildQuestion!=='function'||window.__lousaV70Numbers)return;window.__lousaV70Numbers=true;const old=buildQuestion;buildQuestion=function(q,n){return old.call(this,q,(typeof currentSubjectKey!=='undefined'&&currentSubjectKey==='portuguese'&&q&&q.bookNumber)?q.bookNumber:n)}}
function version(){try{const m=document.querySelector('meta[name="app-version"]');if(m)m.content='70';document.documentElement.dataset.contentVersion='70';document.querySelectorAll('.lousaVersionOnly').forEach(e=>e.textContent='v70')}catch(e){}}
function init(){install();numbers();protect();restoreAll();version();[600,1500,3500].forEach(t=>setTimeout(version,t))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
